### PR TITLE
Remove obsolete stylesheet link tag

### LINKED ISSUE #52: Saving page results in Internal Server Error
I Created a new page, set title, parent and added some content.

When clicking save I got this error:
```
ActionView::Template::Error (undefined method `find_asset' for nil:NilClass):
     5:     <meta charset='<%= ::Rails.application.config.encoding %>' />
     6:     <meta httpequiv="XUACompatible" content="IE=edge,chrome=1" />
     7:     <%= stylesheet_link_tag "wymeditor/skins/refinery/wymiframe", :media => "all" %>
     8:     <%= stylesheet_link_tag "formatting", :media => "all" if Rails.application.assets.find_asset('formatting.css') %>
     9:     <%= stylesheet_link_tag "theme", :media => "all" %>
    10:     <%= javascript_include_tag 'modernizr-min' %>
    11:   </head>
```

I am using (pre-)compiled assets on my production environment.

The error seems to be related to https://github.com/rails/sprockets-rails/issues/311

### PR DESCRIPTION
**Pull request by Unknown-Guy**
Fixes #52

### CODE REVIEW

**Comment by parndt** [comment]
🤔 formatting.css was a hook to allow people to add their site's styling to the visual editor so that it looked similar. We probably don't _need_ it..

**Comment by parndt** [comment]
@Unknown-Guy I think this was fixed by #53 (and also #64)

Is it still a problem for you?

**Comment by Unknown-Guy** [comment]
I think we fixed this by overriding the view and removing the line. Checking for asset existence should work. Closing this then.

**Comment by parndt** [comment]
Thanks a lot!

**Pull request closed without merging**
