### PR TITLE
Require WYMeditor langs folder in wymeditor sprocket manifest

### PR DESCRIPTION
**Pull request by bricesanchez**
#57 breaks the inclusion of supported locales

@evenreven ^

### CODE REVIEW

**Comment by evenreven** [comment]
Yay! I can do a quick test tomorrow. Will you do a 2.2.1 release?

**Comment by parndt** [comment]
Yep, please let us know whether it solves your problem and we'll get it released 😄 thank you

**Comment by evenreven** [comment]
Changed to master branch in my Gemfile and still getting this:

```
ActionView::Template::Error (Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( wymeditor/lang/en.js )` to `config/initializers/assets.rb` and restart your server):
    3:   refinery.current_admin_locale = '<%= current_admin_locale %>';
    4: </script>
    5: <%= javascript_include_tag 'admin' -%>
    6: <%= javascript_include_tag 'refinery/refinery' -%>
    7: <%= javascript_include_tag 'refinery/application' -%>
    8: <% visual_editor_javascripts.each do |js| %>
    9:   <%= javascript_include_tag js %>
```

Here's the relevant bit of my Gemfile.lock, so I think it's pulling the master branch correctly:

```
GIT
  remote: https://github.com/parndt/refinerycms-wymeditor
  revision: bd1771c8f9e3a1bc730ce60f61d6bd38dc97058f
  branch: master
  specs:
    refinerycms-wymeditor (2.2.0)
      refinerycms-core (>= 4.0.0, < 5.0)
 ```

**Comment by bricesanchez** [comment]
I've just tested it on my local in a Rails 6.x dummy_app on `development` and `production` mode and there is no `ActionView::Template::Error`. 

Do you override the `app/assets/javascripts/refinery/wymeditor.js` file in your project?

**Comment by evenreven** [comment]
No, I don't think so. I override the boot options (`custom_visual_editor_boot_options`) with my own admin.js, but that's not the same thing?

In case I'm just completely dense - is this change incompatible with Rails 5.1 (which I'm on)?

**Comment by bricesanchez** [comment]
> is this change incompatible with Rails 5.1 (which I'm on)?

It should be, it's a sprocket manifest.

**Comment by evenreven** [comment]
It should be *in*compatible? If that's not what you mean, I can try to create an empty 5.1 app to weed out weirdnesses in my setup. But I don't have time to do that until after the summer holidays so if you can't recreate this, then never mind me.

**Comment by bricesanchez** [comment]
I'm sorry, i did not read correctly, it should be compatible with Rails 5.1. I don't know why you still have an issue

**Pull request merged**
