### PR TITLE
Fix #2847 in refinerycms

### PR DESCRIPTION
**Pull request by CJBrew**
This is @fixnum's patch for the Stack Error on creating pages.

### CODE REVIEW

**Comment by CJBrew** [comment]
p.s. I hope the merge commits in this PR will disappear if you bring it into your code?  

I could rebase things so that this PR is cleaner.

**Comment by parndt** [comment]
This patch doesn't do anything besides prevent the invocation of the method.

**Comment by CJBrew** [comment]
:+1:  fair enough!

I was trying to understand the original code.

This method? `reserved_words_without_wymiframe.push('wymiframe')`

I can't find `reserved_words_without_wymiframe`, so I guess it's a bit of ruby syntactic "magic". Where does that .push go to?

**Comment by parndt** [comment]
That's what `alias_method_chain` does.  Say you have a method called `reserved_words` and you call `alias_method_chain :reserved_words, :wymiframe` this creates two methods. One called `reserved_words_without_wymiframe` which is the original method and one called `reserved_words_with_wymiframe` which is the method that we've defined.  

So inside `reserved_words_with_wymiframe` we're calling `reserved_words_without_wymiframe` and pushing another reserved word on top of the array that the method returns.  By removing the `alias_method_chain` we just have a method that's never being called which means that the `SystemStackError` goes away but we never get our end goal.

The SystemStackError is happening because the decorators library is loading this file too many times and so we have an `alias_method_chain` on top of an `alias_method_chain`. Eventually the ruby interpreter decides it's an infinite recursion.

**Comment by CJBrew** [comment]
Thanks for the explanation. 

Do you think this could be a bug in the Refinery::Page model rather than the wymeditor?

**Comment by parndt** [comment]
Don't worry, I have a solution that I'm writing up right now.  I'll open a PR for it once I'm done.

**Comment by CJBrew** [comment]
It's the weird edge case failures that are most interesting. Looking forward to see your fix.

**Comment by CJBrew** [comment]
Closed as this is not a fix, but a temporary workaround to stop the error.

**Comment by CJBrew** [comment]
Just seen the pull request has been merged. Thanks! I am fairly sure I understand what you have done there with moving the reserved_words array down to the Page class -- and broadly why it avoids the error.  

What I didn't entirely understand is how that decorator got hit more than once. Is it because of multiple gems loading the same editor?

**Comment by parndt** [comment]
Nah, it's a bug with the decorators library.. unfortunately it's running decorators more than once.

**Comment by parndt** [comment]
@CJBrew  I've fixed the bug with decorators and released version 1.0.4 to address it.

cc @anitagraham you probably care about this too! Happy Australia Day.

**Comment by parndt** [comment]
Here's the commit reference: https://github.com/parndt/decorators/commit/0ff56dac6a54c027992ff7585d65bc904dcc2f8b

**Comment by anitagraham** [comment]
:+1:

**Pull request closed without merging**
